// ingredients for menu bubur & nasi tim
export const MENU_LABU = 'Labu Kuning'
export const MENU_AYAM = 'Daging Ayam'
export const MENU_SEREALIA = 'Serealia'
export const MENU_BIT_ROOT = 'Bit Root'
export const MENU_SAPI = 'Daging Sapi'
export const MENU_KACANG_MERAH = 'Kacang Merah'
export const MENU_KACANG_HIJAU = 'Kacang Hijau'
export const MENU_SALMON = 'Ikan Salmon'
export const MENU_BAYAM = 'Bayam'
export const MENU_TUNA = 'Ikan Tuna'
export const MENU_WORTEL = 'Wortel'
export const MENU_PATIN = 'Ikan Patin'
export const MENU_HATI = 'Hati Sapi'
export const MENU_LELE = 'Ikan Lele'
export const MENU_KAKAP = 'Ikan Kakap'

// flavour for puding & oatmeal
export const FLAVOUR_MANGGO = 'Mangga'
export const FLAVOUR_OREO = 'Oreo'
export const FLAVOUR_TARO = 'Taro'
export const FLAVOUR_GRAPE = 'Anggur'
export const FLAVOUR_ORANGE = 'Orange'
export const FLAVOUR_BANANA_CHOCO = 'Pisang Cokelat'
export const FLAVOUR_VANILLA = 'Vanilla'
export const FLAVOUR_MELON = 'Melon'
export const FLAVOUR_GUAVA = 'Guava'
export const FLAVOUR_BLUEBERRY = 'Blueberry'
export const FLAVOUR_LECI = 'Leci'
export const FLAVOUR_AVOCADO = 'Avocado'
export const FLAVOUR_CHOCO = 'Cokelat'
export const FLAVOUR_MUNG_BEANS = 'Kacang Hijau'
export const FLAVOUR_BANANA = 'Pisang'
export const FLAVOUR_MILO = 'Milo'
export const FLAVOUR_STRAWBERRY = 'Strawberry'
export const FLAVOUR_COCOPANDAN = 'Cocopandan'
